import { StyleSheet, PixelRatio } from 'react-native';

const colorNav = '#2D3336',
      textColor = '#999999';

export default StyleSheet.create({
  Navbar:{
    flex:1,
    width:'100%',
    backgroundColor:colorNav,
    justifyContent:'space-between'
  },
  NavbarUserProfile:{
    flexDirection:'row',
    justifyContent:'center',
    alignItems:'center',
    paddingVertical:15
  },
  imgUser:{
    width:70,
    height:70,
    borderRadius:500,
    resizeMode:'contain'
  },
  infoUser:{
    paddingLeft:10,
    justifyContent:'center',
  },
  contentAddress:{
   flexDirection:'row',
   justifyContent:'center',
   alignItems:'center'
  },
  nameUser:{
    color:'#fff',
    textAlign:'center',
    fontSize:22,
    fontWeight:'700',
    fontFamily:'Montserrat-Regular '
  },
  addressUser:{
    color:textColor,
    textAlign:'center',
    fontSize:15,
    fontFamily:'Montserrat-Regular'
  },
  iconAddress:{
    color:textColor,
    fontSize:15,
    marginRight:6
  },
  NavbarlevelRank:{
    backgroundColor:'#282A2B',
    marginTop:-10,
    display:'flex',
    alignItems:'center'
  },

  contentRank:{
    flexDirection:'row',
    paddingVertical:15
  },
  freelance:{
    color:'#6CA31E',
    fontFamily:'Montserrat-Regular',
    textAlign:'center',
    fontSize:22,
    marginTop:5,
    fontWeight:'600'
  },
  rank:{
    flexDirection:'row',
    alignItems:'center'
  },
  rocket:{
    color:'#008EDF',
    fontSize:22,
    marginLeft:7
  },
  master:{
    color:textColor,
    fontSize:20,
    fontWeight:'300',
    fontFamily:'Montserrat-Regular'
  },
  menu:{
    marginTop:10
  },
  menuItem:{
    padding:15,
    borderBottomColor:'#ccc',
    borderBottomWidth:0.4
  },
  menuItemText:{
    width:'100%',
    color:textColor,
    marginLeft:12,
    fontSize:16,
    fontFamily:'Montserrat-Regular',
  },
  menuItemIcon:{
    color:textColor,
    fontSize:18
  },
  separator:{
    borderWidth:0.5
  },
  options:{
    flexDirection:'row',
    paddingLeft:5
  },
  iconOptions:{
    color:textColor,
    fontSize:20,
    padding:10
  }

});